import type { Metadata } from "next";
// import { ReactNode } from 'react';
import type {AppProps} from 'next/app';
import { Inter } from "next/font/google";
import "../styles/globals.css";
// import  localFont  from '@material-tailwind/react';
// import { createContext } from 'react';
import { SessionProvider } from "next-auth/react";
import { Providers } from "./provider";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Our Peaceland Academy |OPA|",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: [{path:'../public/fonts/Tasman-SemiBold.ttf'},],
  variable: '--font-tasman'
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
// interface RootLayoutProps {
//   children: React.ReactNode;
// }
// export default function RootLayout({ children }: RootLayoutProps)

  return (
    <html lang="en" className={`${myFont.variable} font-tas bg-white`}>
      <head><link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      /></head>
      {/* <body><MaterialTailwindProvider value={value}>{children}</MaterialTailwindProvider></body> */}
      <body>
        {/* <SessionProvider>{children}</SessionProvider> */}
        <Providers>{children}</Providers>
        </body>
    </html>
  );
}
